name: vid_api_server
description: A sample command-line application.
version: 1.0.0
publish_to: none #not intended for pub.dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies: 
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_cors_headers: ^0.1.2 
  firebase_dart: ^1.0.4
  

dev_dependencies:
  lints: ^1.0.0
  http: ^0.13.4
  test: ^1.16.0
